[profile.default]
src = "src"
libs = ["dependencies"] # <= This is important to be added
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
out = "out"
optimizer = true
optimizer_runs = 20_000
solc = "0.8.22"
fs_permissions = [{ access = "read-write", path = "out" }, { access = "read", path = "test/fixtures" }]

[profile.linea]
evm_version = "paris"

[profile.zksync]
compile = true
zksolc = "1.5.12"
verifier="zksync"

[dependencies]
forge-std = "1.9.6"
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"
"@openzeppelin-contracts" = "5.2.0"

