[profile.default]
src = "src"
libs = ["dependencies"] # <= This is important to be added
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
out = "out"
solc = "0.8.22"
fs_permissions = [{ access = "read", path = "out" }, { access = "read", path = "test/fixtures" }]

[dependencies]
forge-std = "1.9.6"
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"
"@openzeppelin-contracts" = "5.2.0"

