[profile.default]
src = "src"
libs = ["lib"]
#ffi = true
#ast = true
#build_info = true
#extra_output = ["storageLayout"]
out = "out"
solc = "0.8.22"
fs_permissions = [{ access = "read", path = "test/vectors"}]
