# This Docker Compose file sets up a local testnet environment for deploying and testing smart contracts using core-v2.
# It defines two services: a local RPC node and a service to deploy contracts.

services:
  # This is the local RPC node that we will use to deploy the contracts.
  node:
    image: core-v2:latest
    ports:
      - "8545:8545"
    command: |
      /bin/sh -c '
        bash ./bin/testnet-config.sh \
          --host 0.0.0.0 \
          --port 8545 \
          --chain 1337 \
          --genesis ./genesis.json \
          --fund-account 0x7C010FD1B3e279ac063d862199484254f27C2C44 \
        && tail -f /dev/null \
      '
    healthcheck:
      test: ["CMD", "curl", "--fail", "-X", "POST", "-H", "Content-Type: application/json", "--data", '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}', "http://localhost:8545"]
      interval: "1s"
      timeout: "10s"
      retries: 10
      start_period: "1s"
    volumes:
      - contracts:/usr/src/app/out-test

  # This is the service that will deploy the contracts.
  deploy-contracts:
    image: core-v2:latest
    depends_on:
      - node
    command: >
      bash ./bin/deploy.sh
        --rpc http://node:8545
        --chain 1337
        --private-key 0x024cf65eb3bc550a1a6675aa21d146d7476fc5b62715d24fb2e0027647a213af
    volumes:
      - contracts:/usr/src/app/out-test

volumes:
  contracts: